### PR TITLE
Adding config for governor settings

### PR DESCRIPTION
**Pull request by drabb**
First off, big thanks for this, it works a charm and saves a bunch of time!

I thought it might be useful to expose a conf setting for the `scaling_governor` - so I added that here.

### CODE REVIEW

**Comment by jothi-prasath** [comment]
you can't change the epp state in performace governor

**Comment by drabb** [comment]
I'm not completely following your comment here.  This PR should allow for setting scaling_governor to a value other than `powersave`.  As I understood it, different permutations of the EPP state and the governor state would allow for fine tuning for better performance or better power consumption.

I have two Ryzen mobile processors available to test on, both show two available settings for the governor, `peformance` and `powersave`.

```
$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
performance powersave
```

**Comment by jothi-prasath** [comment]
i have ryzen 5 5500u mobo processor where i can't change `energy_performance_preference` in `performance` governor.
But i can change the  `energy_performance_preference` in `powersave` governor. 

image
image


can you run these screenshot the output

```
echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
```
```
echo "power" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference
```

**Comment by drabb** [comment]
Indeed I have the same output that you do when attempting to set EPP to `power` when governor is set to `performance`.  System does however allow me to set both to `performance`.  

image

Quick cat to verify that it took
```
$ cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference
performance
$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
performance
```

**Comment by drabb** [comment]
with `powersave` / `balance_power` (on battery) my cpu is capped around 2.7Ghz
with `performance` / `performance` (on AC) my cpu is capped around 3.3Ghz
with `powersave` / `performance` (on AC) my cpu is capped around 3.3Ghz

in my super scientific test, where I'm using the `stress` command and watching `proc/cpuinfo` 😄 there doesn't seem to much difference, at least in CPU clock speeds, between the last two permutations, so perhaps the governor setting is moot in this case.

image
image

As-is this PR should technically work in the case of setting both the governor and EPP to `performance`.  Though it appears there may not be a substantial benefit to doing so.

**Comment by jothi-prasath** [comment]
The `performance` governor is simply EPP where set to `performance` which doesn't make sense. 
we can set the desired EPP between `performance balance_performance balance_power power` in `powersave` governor.
If the user set the `governor_state_for_AC=performance` and `epp_state_for_AC=balance_performance` it won't work.
So defaulting governor to `powersave` is necessary

**Comment by drabb** [comment]
Roger that.  Thanks for rubbering ducking with me friend.

**Pull request closed without merging**
